### ISSUE TITLE
Want cultivar data

### ISSUE THREAD

**Issue by shinkle-lanl** [pi4-uiuc/IndoorOutdoor#2]
Some of the observations are missing cultivar data. Is this data available?

**Comment by dlebauer** [comment]
Please try again... in the terraref dataset there should be at least 75% of records with cultivar information. On BETYdb.org it will be much lower

**Comment by dlebauer** [comment]
Ps because I added these data around 2 today.

**Comment by dlebauer** [comment]
If this resolves the issues please close
